### ISSUE TITLE
Plugin de Sistra ha deixat de funcionar

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#314]
Depèn de "Millores en el Front #289"

Pareix que han desaparegut mètodes de l'api v2 de sistra:

12:21:50,867 ERROR [org.fundaciobit.pluginsib.carpetafront.sistra.SistraCarpetaFrontPlugin] (default task-35) Error llistant trÓmits: org.apache.cxf.s
ervice.factory.ServiceConstructionException: Service class es.caib.zonaper.ws.v2.services.BackofficeFacade does not implement the obtenerElementosExpe
diente method.: javax.xml.ws.WebServiceException: org.apache.cxf.service.factory.ServiceConstructionException: Service class es.caib.zonaper.ws.v2.ser
vices.BackofficeFacade does not implement the obtenerElementosExpediente method.
        at org.apache.cxf.impl//org.apache.cxf.jaxws.ServiceImpl.getPort(ServiceImpl.java:361)
        at org.apache.cxf.impl//org.apache.cxf.jaxws.ServiceImpl.getPort(ServiceImpl.java:350)
        at javax.xml.ws.api@1.0.0.Final-redhat-1//javax.xml.ws.Service.getPort(Service.java:169)
        at deployment.carpeta.ear//es.caib.zonaper.ws.v2.services.BackofficeFacadeService.getBackofficeFacade(BackofficeFacadeService.java:72)
        at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.sistra.SistraCarpetaFrontPlugin.getBackofficeFacade(SistraCarpetaFrontPlugin
.java:430)
        at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.sistra.SistraCarpetaFrontPlugin.getTramits(SistraCarpetaFrontPlugin.java:312
)
        at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.sistra.SistraCarpetaFrontPlugin.getTramitsDebug(SistraCarpetaFrontPlugin.jav
a:396)
        at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.sistra.SistraCarpetaFrontPlugin.getLlistatDeTramitsPage(SistraCarpetaFrontPl
ugin.java:221)
        at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.sistra.SistraCarpetaFrontPlugin.llistatDeTramits(SistraCarpetaFrontPlugin.ja
va:185)
        at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.sistra.SistraCarpetaFrontPlugin.requestCarpetaFront(SistraCarpetaFrontPlugin
.java:121)
        at deployment.carpeta.ear//es.caib.carpeta.pluginsib.carpetafront.api.AbstractCarpetaFrontPlugin.requestCarpetaFront(AbstractCarpetaFrontPlugi
n.java:148)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//es.caib.carpeta.front.controller.AbstractCarpetaFrontModuleController.requestPlugin(Abstrac
tCarpetaFrontModuleController.java:259)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//es.caib.carpeta.front.controller.AbstractCarpetaFrontModuleController.processServlet(Abstra
ctCarpetaFrontModuleController.java:192)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//es.caib.carpeta.front.controller.AbstractCarpetaFrontModuleController.doPost(AbstractCarpet
aFrontModuleController.java:140)
        at javax.servlet.api@1.0.0.Final-redhat-1//javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
        at javax.servlet.api@1.0.0.Final-redhat-1//javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at io.opentracing.contrib.opentracing-jaxrs2@0.1.7.redhat-00001//io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishi
ngFilter.java:55)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainPr
oxy.java:317)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSe
curityInterceptor.java:127)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(Filter
SecurityInterceptor.java:91)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainPr
oxy.java:331)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTransl
ationFilter.java:114)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainPr
oxy.java:331)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagement
Filter.java:137)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainPr
oxy.java:331)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(Anon
ymousAuthenticationFilter.java:111)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainPr
oxy.java:331)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilte
r(SecurityContextHolderAwareRequestFilter.java:170)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainPr
oxy.java:331)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCache
AwareFilter.java:63)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainPr
oxy.java:331)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFi
lter(AbstractAuthenticationProcessingFilter.java:200)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainPr
oxy.java:331)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.j
ava:116)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainPr
oxy.java:331)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainPr
oxy.java:331)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFil
ter.java:66)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainPr
oxy.java:331)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(Security
ContextPersistenceFilter.java:105)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainPr
oxy.java:331)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doF
ilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainPr
oxy.java:331)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:21
4)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.j
ava:347)
        at deployment.carpeta.ear.carpeta-front-1.1.7.war//org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:26
3)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecuri
tyRoleHandler.java:62)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandl
er.java:36)
        at org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleReque
st(SecurityContextAssociationHandler.java:78)
        at io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInfo
rmationAssociationHandler.java:132)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(Servlet
AuthenticationCallHandler.java:57)
        at io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidential
ityHandler.java:46)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(
ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMecha
nismsHandler.java:60)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(Cached
AuthenticatedSessionHandler.java:77)
        at io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHan
dler.java:50)
        at io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractS
ecurityContextAssociationHandler.java:43)
        at io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCC
ontextIdHandler.java:61)
        at io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleReques
t(GlobalRequestControllerHandler.java:68)
        at io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.
java:292)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)

        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContext
ThreadSetupAction.java:48)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.
java:43)
        at org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$creat
e$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThrea
dSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThrea
dSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThrea
dSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThrea
dSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThrea
dSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.jav
a:272)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)

        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.jav
a:104)
        at io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
        at io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
        at org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
        at org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
        at org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: Service class es.caib.zonaper.ws.v2.services.BackofficeFacade does not impleme
nt the obtenerElementosExpediente method.
        at org.apache.cxf.impl//org.apache.cxf.jaxws.JAXWSMethodDispatcher.bind(JAXWSMethodDispatcher.java:69)
        at org.apache.cxf.impl//org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.bindOperation(JaxWsServiceFactoryBean.java:278)
        at org.apache.cxf.impl//org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.initializeWSDLOperation(JaxWsServiceFactoryBean.java:251)
        at org.apache.cxf.impl//org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.initializeWSDLOperations(ReflectionServiceFactoryBean
.java:668)
        at org.apache.cxf.impl//org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.initializeWSDLOperations(JaxWsServiceFactoryBean.java:287)
        at org.apache.cxf.impl//org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromWSDL(ReflectionServiceFactoryBean.jav
a:418)
        at org.apache.cxf.impl//org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.initializeServiceModel(ReflectionServiceFactoryBean.j
ava:528)
        at org.apache.cxf.impl//org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.create(ReflectionServiceFactoryBean.java:263)
        at org.apache.cxf.impl//org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.create(JaxWsServiceFactoryBean.java:199)
        at org.apache.cxf.impl//org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:103)
        at org.apache.cxf.impl//org.apache.cxf.frontend.ClientFactoryBean.create(ClientFactoryBean.java:91)
        at org.apache.cxf.impl//org.apache.cxf.frontend.ClientProxyFactoryBean.create(ClientProxyFactoryBean.java:159)
        at org.apache.cxf.impl//org.apache.cxf.jaxws.JaxWsProxyFactoryBean.create(JaxWsProxyFactoryBean.java:142)
        at org.apache.cxf.impl//org.apache.cxf.jaxws.ServiceImpl.createPort(ServiceImpl.java:493)
        at org.jboss.ws.jaxws-client@5.2.4.Final-redhat-00001//org.jboss.wsf.stack.cxf.client.ProviderImpl$JBossWSServiceImpl.createPort(ProviderImpl.
java:580)
        at org.apache.cxf.impl//org.apache.cxf.jaxws.ServiceImpl.getPort(ServiceImpl.java:359)
        ... 97 more
Caused by: java.lang.NoSuchMethodException: es.caib.zonaper.ws.v2.services.BackofficeFacade.obtenerElementosExpediente(es.caib.zonaper.ws.v2.model.ele
mentoexpediente.FiltroElementosExpediente, java.lang.Integer, java.lang.Integer)
        at java.base/java.lang.Class.getMethod(Class.java:2108)
        at org.apache.cxf.impl//org.apache.cxf.jaxws.JAXWSMethodDispatcher.getImplementationMethod(JAXWSMethodDispatcher.java:89)
        at org.apache.cxf.impl//org.apache.cxf.jaxws.JAXWSMethodDispatcher.bind(JAXWSMethodDispatcher.java:56)
        ... 112 more

**Comment by jagarcia-fundaciobit** [comment]
Solucionat. He marcat la dependencia com  a provided dins del pom.xml perquè es veu que entrava en conflicte amb una altra llibreria carregada anteriorment.

**Comment by jagarcia-fundaciobit** [comment]
S'ha revisat la funcionalitat de mostrarModal.
