### ISSUE TITLE
Quan expira la sessió es produeix un NullPointer

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#382]
Depèn de "Millores en el Front #339"

Pareix que en el codi hi ha un Null Pointer no controlat quan la sessió expira en el front. tambe passa quan li dones al boto de Sortir del menú deslissant.

10:01:55,504 INFO  [es.caib.carpeta.front.security.LoginController] (default task-114) Dentro de salir
10:01:55,505 INFO  [es.caib.carpeta.front.security.LoginController] (default task-114)  XXX XYZ  BASE URL LOGOUT => null
10:01:56,146 INFO  [es.caib.carpeta.front.service.SecurityServiceImpl] (default task-114) Url LOGOUT: https://dev.caib.es/loginibfront/redirigirLogout
Clave.html?idSesion=YDOQKWMV-2M0MNRT8-T8LJC9HT
10:01:56,171 INFO  [org.hibernate.hql.internal.QueryTranslatorFactoryInitiator] (default task-114) HHH000397: Using ASTQueryTranslatorFactory
10:01:56,173 ERROR [es.caib.carpeta.front.controller.InicioController] (default task-114) null: java.lang.NullPointerException
        at deployment.carpeta.ear.carpeta-front.war//es.caib.carpeta.front.controller.InicioController.triarEntitat(InicioController.java:114)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.jav
a:205)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMe
thod.java:133)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHand
le(ServletInvocableHandlerMethod.java:97)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerM
ethod(RequestMappingHandlerAdapter.java:854)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal
(RequestMappingHandlerAdapter.java:765)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMet
hodAdapter.java:85)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.api@1.0.0.Final-redhat-1//javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.api@1.0.0.Final-redhat-1//javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at io.opentracing.contrib.opentracing-jaxrs2@0.1.7.redhat-00001//io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishi
ngFilter.java:55)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.ja

**Comment by jpernia-fundaciobit** [comment]
He intentat replicar l'error però no he pogut. He povat amb una única entitat, loguejat i sense loguejar. Esperant a que acabi la sessió o tancant la sessió des del menú. També amb vàries entitats actives, canviant entitats, etc.
S'hauria de mirar si torna a passar de mirar quina configuració hi ha, número d'entitats, propietat global "defaultentity" definida o no ...

**Comment by jpernia-fundaciobit** [comment]
S'intenta controllar aquest NullPointer mirant a LoginController si al sortir de la zona privada, el codiEntitat és null, se li assigna el que hi ha a defaultEntity.

**Comment by scalafat-dgtic** [comment]
A veure si puc donar més informació sobre aquest tema, perquè segueix succeint:

M'ha expirat la sessió, no sé quant de temps fa que la tenia expirada però pot ser més de 30 minuts, i he pitjat l'OK del missatge. M'ha redirigit a https://dev.caib.es/error (he obert issue #399) i en tornar a entrar a /carpetafront i loguejar-me dins Carpeta amb LoginIB m'ha sortit la següent pantalla amb el següento error:

![image](https://user-images.githubusercontent.com/44995350/109815215-ad6f6d00-7c2f-11eb-9864-e5b7b68f5282.png)


2021-03-03 14:44:26,054 ERROR [es.caib.carpeta.front.controller.WebUIController] (default task-24) null: java.lang.NullPointerException
	at deployment.carpeta.ear.carpeta-front.war//es.caib.carpeta.front.controller.WebUIController.getEntitatNom(WebUIController.java:817)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

**Comment by jpernia-fundaciobit** [comment]
Aquest error el dóna a un troç de codi que s'ha de revisar a l'issue "Modificar l'entitat on es creen els accessos #395".
Per tant, es tanca.
