### ISSUE TITLE
Plugin de Policia no funciona a la DGMAD

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#430]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #512"

Està relacionada amb "Obtenció i mostratge de dades del ciutadà #221" 

SIMO CALAFAT: Ara he posat els dos plugins així com m'has dit. No puc fer funcionar el de Policia. Me dona el següent error:

2021-03-15 09:22:47,592 ERROR [org.fundaciobit.pluginsib.carpetafront.pinbalpolicia.PinbalPoliciaCarpetaFrontPlugin] (default task-321) Error consultant Dades d'Identitat a la Policia: Fault string, and possibly fault code, not set: javax.xml.ws.soap.SOAPFaultException: Fault string, and possibly fault code, not set
	at org.apache.cxf.impl//org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:161)
	at com.sun.proxy.$Proxy747.peticionSincrona(Unknown Source)
	at deployment.carpeta.ear//es.caib.scsp.pinbal.ws.recobriment.client.RecobrimentClient.peticionSincrona(RecobrimentClient.java:192)
	at deployment.carpeta.ear//es.caib.scsp.pinbal.ws.recobriment.client.RecobrimentClient.peticionSincrona(RecobrimentClient.java:160)
	at deployment.carpeta.ear//es.caib.scsp.pinbal.ws.recobriment.facade.RecobrimentFacade.peticionSincrona(RecobrimentFacade.java:70)
	at deployment.carpeta.ear//es.caib.scsp.pinbal.ws.recobriment.facade.RecobrimentFacade.peticionSincrona(RecobrimentFacade.java:75)
	at deployment.carpeta.ear//es.caib.scsp.pinbal.ws.recobriment.facade.RecobrimentFacade.peticionSincrona(RecobrimentFacade.java:155)
	at deployment.carpeta.ear//es.caib.carpeta.pinbal.ws.recobriment.facade.SVDDGPCIWS02v3RecobrimentFacade.peticionSincronaEspecifica(SVDDGPCIWS02v3RecobrimentFacade.java:93)
	at deployment.carpeta.ear//es.caib.carpeta.pinbal.ws.recobriment.facade.SVDDGPCIWS02v3RecobrimentFacade.peticionSincrona(SVDDGPCIWS02v3RecobrimentFacade.java:172)
	at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.pinbalpolicia.PinbalPoliciaCarpetaFrontPlugin.documentIdentitatRestService(PinbalPoliciaCarpetaFrontPlugin.java:327)
	at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.pinbalpolicia.PinbalPoliciaCarpetaFrontPlugin.requestCarpetaFront(PinbalPoliciaCarpetaFrontPlugin.java:113)
	at deployment.carpeta.ear//es.caib.carpeta.pluginsib.carpetafront.api.AbstractCarpetaFrontPlugin.requestCarpetaFront(AbstractCarpetaFrontPlugin.java:150)
	at deployment.carpeta.ear.carpeta-front.war//es.caib.carpeta.front.controller.AbstractCarpetaFrontModuleController.requestPlugin(AbstractCarpetaFrontModuleController.java:259)
	at deployment.carpeta.ear.carpeta-front.war//es.caib.carpeta.front.controller.AbstractCarpetaFrontModuleController.processServlet(AbstractCarpetaFrontModuleController.java:192)
	at deployment.carpeta.ear.carpeta-front.war//es.caib.carpeta.front.controller.AbstractCarpetaFrontModuleController.doGet(AbstractCarpetaFrontModuleController.java:135)
	at javax.servlet.api@1.0.0.Final-redhat-1//javax.servlet.http.HttpServlet.service(HttpServlet.java:686)

[...]
Caused by: java.lang.NullPointerException
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:496)
	at java.base/java.util.HashMap.<init>(HashMap.java:485)

[...]

2021-03-15 09:22:47,596 INFO  [org.fundaciobit.pluginsib.carpetafront.pinbalpolicia.PinbalPoliciaCarpetaFrontPlugin] (default task-321) 
DADES POLICIA JSON: {"error":"Error consultant Dades d\u0027Identitat a la Policia: Fault string, and possibly fault code, not set"}

**Comment by jagarcia-fundaciobit** [comment]
Amb el desenvolupament de la issue "Adaptar la cridada al Client REST del plugin de pinbalpolicia #523", el plugin ja funciona.
