### ISSUE TITLE
Excepció al log al mostrar Logs

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#451]
Depèn de "Millores en el codi del BACK #526"

Pareix com si alguna referència ja no existis. Controlar-ho i posar  KeyValues no existents.

![imagen](https://user-images.githubusercontent.com/17084256/112829466-76a34000-9091-11eb-81c4-51925b2d42fd.png)

13:13:22,823 WARN  [es.caib.carpeta.back.controller.superadmin.LogCarpetaSuperAdminController] (default task-9) Al cridar al mapping per la clau '2006' ha retornat un valor null.: java.lang.Exception
        at deployment.carpeta.ear.carpeta-back.war//org.fundaciobit.genapp.common.web.controller.CommonBaseController.fillValuesToGroupByItems(CommonBaseController.java:324)
        at deployment.carpeta.ear.carpeta-back.war//es.caib.carpeta.back.controller.webdb.LogCarpetaController.fillReferencesForList(LogCarpetaController.java:207)
        at deployment.carpeta.ear.carpeta-back.war//es.caib.carpeta.back.controller.webdb.LogCarpetaController.llistat(LogCarpetaController.java:162)
        at deployment.carpeta.ear.carpeta-back.war//es.caib.carpeta.back.controller.webdb.LogCarpetaController.llistatPaginat(LogCarpetaController.java:85)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.method.support.InvocableHandlerMethod.invoke

**Comment by jpernia-fundaciobit** [comment]
S'ha pogut replicar el WARNING que apareix.
Això passa quan hi ha un log d'un plugin i el plugin s'elimina de Carpeta, s'esborra des del rol Superadmin.
Hi hauria 2 possibilitats per a que no aparegui aquesta excepció:
- Que quan s'esborra un plugin de Carpeta també s'esborrin els seus logs (tal vegada no té sentit que quedin logs d'un plugin que no existeix).
- Controlar des del controller dels logs que si un plugin no existeix, no cerqui la seva informació als plugins.
Com que és cosa de Genapp, es torna a deixar a To Do.

**Comment by jpernia-fundaciobit** [comment]
Solventat al issue  #619. Està fet al Plugin i en aquest s'esborren Logs, Accessos i Avisos.
