### ISSUE TITLE
Al perdre sessió al front va a /error

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#459]
Depèn de "Millores en el Front #423"

Error quan despres d'expirar sessió intent fer alguna cosa i va /error. Per reproduir-ho no tenir entitat per defecte i esperar a una expiració de sessió. També em passa si faig login al front i despres faig un deploy en calent del servidor. Vaig a sortir i es produeix l'error de la captura. També adjunt excepció del servidor.

S'hauria de gestionar quan va a /carpetafront/e/null: netejar la sessió i redireccionar a selecció d'entitats.

`13:14:22,640 INFO  [es.caib.carpeta.front.security.LoginController] (default task-62) Dentro de salir
13:14:22,641 INFO  [es.caib.carpeta.front.security.LoginController] (default task-62)  XXX XYZ  BASE URL LOGOUT => null
13:14:22,641 INFO  [es.caib.carpeta.front.security.LoginController] (default task-62) WWWWWWWWWWWWWW Codi entitat: null WWWWWWWWWWWWWWWWWW
13:14:22,643 INFO  [es.caib.carpeta.front.service.SecurityServiceImpl] (default task-62) Url LOGOUT: null/salir
13:14:22,646 INFO  [es.caib.carpeta.front.security.LoginController] (default task-62) WWWWWWWWWWWWWW entitat es null, posam DefaultEntity: nullWWWWWWWWWWWWWWWWWW
13:14:22,661 ERROR [es.caib.carpeta.front.controller.InicioController] (default task-62) null: java.lang.NullPointerException
        at deployment.carpeta.ear.carpeta-front.war//es.caib.carpeta.front.controller.InicioController.triarEntitat(InicioController.java:124)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)`

...

`13:14:22,666 ERROR [io.undertow.request] (default task-62) UT005023: Exception handling request to **/carpetafront/e/null:** org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: UT010019: Response already commited
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.api@1.0.0.Final-redhat-1//javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.api@1.0.0.Final-redhat-1//javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at io.opentracing.contrib.opentracing-jaxrs2@0.1.7.redhat-00001//io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:55)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:33`

![imagen](https://user-images.githubusercontent.com/17084256/113136171-52776880-9223-11eb-930f-585a8edf8c68.png)

**Comment by jpernia-fundaciobit** [comment]
El cas descrit primer (expiració de sessiço sense cap entitat per defecte, que redirecciona a error) no s'ha pogut reproduir.
En le segon cas (deploy en calent del servidor) sí que s'ha replicat i s'ha corregit.
