### ISSUE TITLE
Plugin de Keycloak no funciona dins de l'entorn JBoss

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#485]
Depèn de "Modificacions en el core de l'aplicació (utils, bbdd,ejbs, plugins, ... ) #481"

Quan es configura Carpeta per funciona contra KeyCloak i s'utilitza el Plugin de User Information, aquest no funciona a llança un error "referenced from a method is not visible from class loader".

Es parla d'aquest bug en aquests enllaços:

- https://github.com/spring-projects/spring-amqp/issues/967
- https://github.com/spring-projects/spring-amqp/issues/1008
- https://stackoverflow.com/questions/49113207/completablefuture-forkjoinpool-set-class-loader
- https://github.com/spring-projects/spring-framework/issues/18271

En els comentaris anteriors proposen solucions però jo no les he pogut aplicar, ja que l'API de KeyCloak s'ofereix com a llibreria. Com a solució no se si intentaria crear un mini Client Rest per atacar a l'API de KeyCloak.

Error al intentar donar d'alta manualment un usuari des de la Gestió d'Usuaris de Super Admin:

`09:04:33,083 ERROR [es.caib.carpeta.back.utils.PluginUserInformationUtils] (default task-1) Error intentant obtenir informaci¾ de l'usari u999000: org.keycloak.representations.AccessTokenResponse referenced from a method is not visible from class loader: java.lang.IllegalArgumentException: org.keycloak.representations.AccessTokenResponse referenced from a method is not visible from class loader
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.ensureVisible(Proxy.java:858)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.validateProxyInterfaces(Proxy.java:700)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:627)
        at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$1(Proxy.java:426)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
        at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:424)
        at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1006)
        at org.jboss.resteasy.resteasy-jaxrs@3.6.1.SP8-redhat-00001//org.jboss.resteasy.client.jaxrs.ProxyBuilder.proxy(ProxyBuilder.java:99)
        at org.jboss.resteasy.resteasy-jaxrs@3.6.1.SP8-redhat-00001//org.jboss.resteasy.client.jaxrs.ProxyBuilder.build(ProxyBuilder.java:166)
        at org.jboss.resteasy.resteasy-jaxrs@3.6.1.SP8-redhat-00001//org.jboss.resteasy.client.jaxrs.internal.ClientWebTarget.proxy(ClientWebTarget.java:93)
        at deployment.carpeta.ear//org.keycloak.admin.client.token.TokenManager.<init>(TokenManager.java:55)
        at deployment.carpeta.ear//org.keycloak.admin.client.Keycloak.<init>(Keycloak.java:59)
        at deployment.carpeta.ear//org.keycloak.admin.client.KeycloakBuilder.build(KeycloakBuilder.java:147)
        at deployment.carpeta.ear//org.fundaciobit.pluginsib.userinformation.keycloak.KeyCloakUserInformationPlugin.getKeyCloakConnection(KeyCloakUserInformationPlugin.java:112)
        at deployment.carpeta.ear//org.fundaciobit.pluginsib.userinformation.keycloak.KeyCloakUserInformationPlugin.getKeyCloakConnectionForUsers(KeyCloakUserInformationPlugin.java:95)
        at deployment.carpeta.ear//org.fundaciobit.pluginsib.userinformation.keycloak.KeyCloakUserInformationPlugin.getUserInfoByUserName(KeyCloakUserInformationPlugin.java:232)
        at deployment.carpeta.ear.carpeta-back.war//es.caib.carpeta.back.utils.PluginUserInformationUtils.getUserInfoFromUserInformation(PluginUserInformationUtils.java:90)
        at deployment.carpeta.ear.carpeta-back.war//es.caib.carpeta.back.controller.superadmin.UsuariSuperAdminController.checkUsuariPost(UsuariSuperAdminController.java:103)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)`

Error de Login al recuperar informació d'un Usuari no donat d'alta:

`09:14:55,179 ERROR [es.caib.carpeta.back.utils.PluginUserInformationUtils] (default task-10) Error intentant obtenir informaci¾ de l'usari u999000: org.keycloak.representations.AccessTokenResponse referenced from a method is not visible from class loader: java.lang.IllegalArgumentException: org.keycloak.representations.AccessTokenResponse referenced from a method is not visible from class loader
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.ensureVisible(Proxy.java:858)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.validateProxyInterfaces(Proxy.java:700)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:627)
        at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$1(Proxy.java:426)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
        at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:424)
        at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1006)
        at org.jboss.resteasy.resteasy-jaxrs@3.6.1.SP8-redhat-00001//org.jboss.resteasy.client.jaxrs.ProxyBuilder.proxy(ProxyBuilder.java:99)
        at org.jboss.resteasy.resteasy-jaxrs@3.6.1.SP8-redhat-00001//org.jboss.resteasy.client.jaxrs.ProxyBuilder.build(ProxyBuilder.java:166)
        at org.jboss.resteasy.resteasy-jaxrs@3.6.1.SP8-redhat-00001//org.jboss.resteasy.client.jaxrs.internal.ClientWebTarget.proxy(ClientWebTarget.java:93)
        at deployment.carpeta.ear//org.keycloak.admin.client.token.TokenManager.<init>(TokenManager.java:55)
        at deployment.carpeta.ear//org.keycloak.admin.client.Keycloak.<init>(Keycloak.java:59)
        at deployment.carpeta.ear//org.keycloak.admin.client.KeycloakBuilder.build(KeycloakBuilder.java:147)
        at deployment.carpeta.ear//org.fundaciobit.pluginsib.userinformation.keycloak.KeyCloakUserInformationPlugin.getKeyCloakConnection(KeyCloakUserInformationPlugin.java:112)
        at deployment.carpeta.ear//org.fundaciobit.pluginsib.userinformation.keycloak.KeyCloakUserInformationPlugin.getKeyCloakConnectionForUsers(KeyCloakUserInformationPlugin.java:95)
        at deployment.carpeta.ear//org.fundaciobit.pluginsib.userinformation.keycloak.KeyCloakUserInformationPlugin.getUserInfoByUserName(KeyCloakUserInformationPlugin.java:232)
        at deployment.carpeta.ear.carpeta-back.war//es.caib.carpeta.back.utils.PluginUserInformationUtils.getUserInfoFromUserInformation(PluginUserInformationUtils.java:90)
        at deployment.carpeta.ear.carpeta-back.war//es.caib.carpeta.back.security.AuthenticationSuccessListener.onApplicationEvent(AuthenticationSuccessListener.java:186)
        at deployment.carpeta.ear.carpeta-back.war//es.caib.carpeta.back.security.AuthenticationSuccessListener.onApplicationEvent(AuthenticationSuccessListener.java:41)
        at deployment.carpeta.ear.carpeta-back.war//org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at deployment.carpeta.ear.carpeta-back.war//org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at deployment.carpeta.ear.carpeta-back.war//org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at deployment.carpeta.ear.carpeta-back.war//org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
        at deployment.carpeta.ear.carpeta-back.war//org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
        at deployment.carpeta.ear.carpeta-back.war//org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.successfulAuthentication(AbstractPreAuthenticatedProcessingFilter.java:241)
        at deployment.carpeta.ear.carpeta-back.war//org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doAuthenticate(AbstractPreAuthenticatedProcessingFilter.java:185)
        at deployment.carpeta.ear.carpeta-back.war//org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:118)`

**Comment by anadal-fundaciobit** [comment]
Al final ha passat el següent:
     (1) JBoss 7.2 funciona a base de mòduls, per exemple el de hibernate o el de resteasy.
     (2) Des del RestEasy de JBoss s'intentava accedir a una Classe de KeyCloak els jars del qual es trobaven a carpeta.ear
     (3) Lllançava un error de que la classe keycloak NO ERA VISIBLE, no llançava un ClassNotFount sinó un "is not visible from class loader"
     (4) Al final vaig caure que tenim el JBoss parxejat amb el mòdul de keycloak per fer l'autenticació. 
     (5) Explicació de l'error. Des de Resteasy del core s'intentava accedir a una classe KeyCloak que es trobava en un mòdul intern de JBoss. Com que des de carpeta no s'havia indicat res, JBoss trobava la classe per com que no s'havi explicitament donat permis pel mòdul KeyCloak indicava "que no era visible"
    (6) Solució: Afegir els mòduls de keycloak al fitxer [carpeta-ear]\src\main\application\META-INF\jboss-deployment-structure.xml
