### ISSUE TITLE
Error de Sessió al usar una Carpeta connectada a KeyCloak

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#542]
Depèn de "Millores en el codi del BACK #526"

Error de Sessió al usar una Carpeta connectada a KeyCloak

![imagen](https://user-images.githubusercontent.com/17084256/125271959-95a9a300-e30b-11eb-8e25-106f674f119c.png)

```
Caused by: java.lang.IllegalStateException: No session attribute 'entitatAdmin' found
	at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.util.WebUtils.getRequiredSessionAttribute(WebUtils.java:320)
	at deployment.carpeta.ear.carpeta-back.war//es.caib.carpeta.back.controller.adminentitat.AdminEntitatController.option1(AdminEntitatController.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854)
	at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765)
	at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at deployment.carpeta.ear.carpeta-back.war//org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	... 95 more
```

**Comment by anadal-fundaciobit** [comment]
Commit 1c7608c277d47aa33b22fa3d758cb488fb30d149

**Comment by anadal-fundaciobit** [comment]
Solucionat.
