### ISSUE TITLE
Error NullPointerException al plugin de Sistra

### ISSUE THREAD

**Issue by jagarcia-fundaciobit** [GovernIB/carpeta#576]
Fent una cerca de tràmits al plugin de Sistra,  amb dates des de 01/01/2019 fins avui me retorna una pantalla en blanc (no surt el missatge d'error).

Els logs diuen el següent:

`2021-09-08 09:27:15,329 ERROR [org.fundaciobit.pluginsib.carpetafront.sistra.SistraCarpetaFrontPlugin] (default task-33) Error llistant tràmits: null: java.lang.NullPointerException
	at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.sistra.TramitePersistenteGenerico.esRegistrado(TramitePersistenteGenerico.java:126)
	at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.sistra.TramitePersistenteGenerico.<init>(TramitePersistenteGenerico.java:202)
	at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.sistra.SistraCarpetaFrontPlugin.getTramits(SistraCarpetaFrontPlugin.java:409)
	at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.sistra.SistraCarpetaFrontPlugin.getTramitsDebug(SistraCarpetaFrontPlugin.java:451)
	at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.sistra.SistraCarpetaFrontPlugin.getLlistatDeTramitsPage(SistraCarpetaFrontPlugin.java:252)
	at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.sistra.SistraCarpetaFrontPlugin.llistatDeTramits(SistraCarpetaFrontPlugin.java:216)
	at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.sistra.SistraCarpetaFrontPlugin.requestCarpetaFront(SistraCarpetaFrontPlugin.java:127)
	at deployment.carpeta.ear//es.caib.carpeta.pluginsib.carpetafront.api.AbstractCarpetaFrontPlugin.requestCarpetaFront(AbstractCarpetaFrontPlugin.java:231`

**Comment by jagarcia-fundaciobit** [comment]
Corregit.
