### ISSUE TITLE
Problemes trobats a la versió 1.1.14 a Producció

### ISSUE THREAD

**Issue by jpernia-fundaciobit** [GovernIB/carpeta#617]
Com a administrador
Vull eliminar els errors que van sortint a Producció
Per tal de minimitzar problemes a l'aplicació

- No troba imatges de les taules de cerca. 
- Error al carregar jquery-3.5.0.js al plugin de Regweb32.
- I error que apareix als logs:
2021-11-16 21:12:20,411 ERROR [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 2) WFLYDS0012: el escáner de /app/jboss-7.2/server/jboss01/deployments presentó una excepción: java.lang.RuntimeException: WFLYDS0032: No logró listar archivos en el directorio /app/jboss-7.2/server/jboss01/deployments. Verifique que el contenido del directorio se leíble.
	at org.jboss.as.deployment-scanner@6.0.11.Final-redhat-00001//org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.listDirectoryChildren(FileSystemDeploymentService.java:1365)
	at org.jboss.as.deployment-scanner@6.0.11.Final-redhat-00001//org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.scanDirectory(FileSystemDeploymentService.java:846)
	at org.jboss.as.deployment-scanner@6.0.11.Final-redhat-00001//org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.scan(FileSystemDeploymentService.java:598)
	at org.jboss.as.deployment-scanner@6.0.11.Final-redhat-00001//org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.scan(FileSystemDeploymentService.java:493)
	at org.jboss.as.deployment-scanner@6.0.11.Final-redhat-00001//org.jboss.as.server.deployment.scanner.FileSystemDeploymentService$DeploymentScanRunnable.run(FileSystemDeploymentService.java:255)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: java.nio.file.FileSystemException: /app/jboss-7.2/server/jboss01/deployments: Demasiados ficheros abiertos
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:604)
	at org.jboss.as.deployment-scanner@6.0.11.Final-redhat-00001//org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.listDirectoryChildren(FileSystemDeploymentService.java:1358)
	... 11 more

**Comment by jagarcia-fundaciobit** [comment]
Modificació del servei que proporciona les estadístiques d'accesos de CARPETA al portal de dades obertes perquè agafi correctament la data d'inici amb el timezone correcte.

**Comment by jpernia-fundaciobit** [comment]
El darrer punt està pendent de que ho miri Serveis Web

**Comment by jpernia-fundaciobit** [comment]
Tancat perquè no s'han tornat a detectar problemes d'aquests.
