### ISSUE TITLE
Problema de JSON amb les Notificacions de Sistra 1

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#629]
Apareix el següent error al llegir Notificacions de Sistra 1 disn de carpeta:

12:27:12,343 INFO  [org.apache.cxf.common.jaxb.JAXBUtils] (default task-6) Failed to create MinimumEscapeHandler
12:27:12,380 ERROR [org.fundaciobit.pluginsib.carpetafront.notificacionssistra.NotificacionsSistraCarpetaFrontPlugin] (default task-6) Error llistant notificacions Sistra: Attempted to serialize java.lang.Class: java.lang.String. Forgot to register a type adapter?: java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: java.lang.String. Forgot to register a type adapter?
        at deployment.carpeta.ear//com.google.gson.internal.bind.TypeAdapters$1.write(TypeAdapters.java:73)
        at deployment.carpeta.ear//com.google.gson.internal.bind.TypeAdapters$1.write(TypeAdapters.java:69)
        at deployment.carpeta.ear//com.google.gson.TypeAdapter$1.write(TypeAdapter.java:191)
        at deployment.carpeta.ear//com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at deployment.carpeta.ear//com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
        at deployment.carpeta.ear//com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
        at deployment.carpeta.ear//com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at deployment.carpeta.ear//com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$

**Comment by anadal-fundaciobit** [comment]
El problema estava en que s'utilitzava una classe POJO de l'API del WS de SISTRA.
