### ISSUE TITLE
Controlar error puntual atacant l'API de NOTIB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/carpeta#729]
De forma aleatòria, algunes cridades a l'API de NOTIB fallen. Pareix com si enlloc de retornar un error JSON, el servidor redirigis la la pàgina de login WEB.
Intentar captura l'error aquest error i si es el cas descrit abans llavors fer un reintent.

```
2022-11-14 09:36:14,492 ERROR [org.fundaciobit.pluginsib.carpetafront.notib.NotibCarpetaFrontPlugin] (default task-90) AbstractPluginFullUtilities::errorREST() com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">

<head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Govern de les Illes Balears</title>
        
        <!-- css -->
        <link href="j_security_check_resource/estilos/estils_intranet.css" rel="stylesheet" type="text/css" media="screen" />
        <!-- /css -->
        
        <script type="text/java"[truncated 4371 chars]; line: 1, column: 2]: java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">

<head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Govern de les Illes Balears</title>
        
        <!-- css -->
        <link href="j_security_check_resource/estilos/estils_intranet.css" rel="stylesheet" type="text/css" media="screen" />
        <!-- /css -->
        
        <script type="text/java"[truncated 4371 chars]; line: 1, column: 2]
        at deployment.carpeta.ear//es.caib.notib.client.NotificacioRestClientV2.notificacionsByTitular(NotificacioRestClientV2.java:275)
        at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.notib.NotibCarpetaFrontPlugin.consultaTotes(NotibCarpetaFrontPlugin.java:1786)
        at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.notib.NotibCarpetaFrontPlugin.requestCarpetaFront(NotibCarpetaFrontPlugin.java:145)
        at deployment.carpeta.ear//es.caib.carpeta.pluginsib.carpetafront.api.AbstractCarpetaFrontPlugin.requestCarpetaFront(AbstractCarpetaFrontPlugin.java:231)
        at deployment.carpeta.ear.carpeta-front.war//es.caib.carpeta.front.controller.AbstractCarpetaFrontModuleController.requestPlugin(AbstractCarpetaFrontModuleController.java:449)
        at deployment.carpeta.ear.carpeta-front.war//es.caib.carpeta.front.controller.AbstractCarpetaFrontModuleController.processServlet(AbstractCarpetaFrontModuleController.java:328)
        at deployment.carpeta.ear.carpeta-front.war//es.caib.carpeta.front.controller.AbstractCarpetaFrontModuleController.doGet(AbstractCarpetaFrontModuleController.java:270)
        at [javax.servlet.api@1.0.0.Final-redhat-1//javax.servlet.http.HttpServlet.service](mailto:javax.servlet.api@1.0.0.Final-redhat-1//javax.servlet.http.HttpServlet.service)(HttpServlet.java:686)
        at [javax.servlet.api@1.0.0.Final-redhat-1//javax.servlet.http.HttpServlet.service](mailto:javax.servlet.api@1.0.0.Final-redhat-1//javax.servlet.http.HttpServlet.service)(HttpServlet.java:791)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletHandler.handleRequest](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletHandler.handleRequest)(ServletHandler.java:74)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter)(FilterHandler.java:129)
        at [io.opentracing.contrib.opentracing-jaxrs2@0.1.7.redhat-00001//io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter](mailto:io.opentracing.contrib.opentracing-jaxrs2@0.1.7.redhat-00001//io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter)(SpanFinishingFilter.java:55)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.core.ManagedFilter.doFilter](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.core.ManagedFilter.doFilter)(ManagedFilter.java:61)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter)(FilterHandler.java:131)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
        at deployment.carpeta.ear.carpeta-front.war//org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.core.ManagedFilter.doFilter](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.core.ManagedFilter.doFilter)(ManagedFilter.java:61)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter)(FilterHandler.java:131)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler.handleRequest](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.FilterHandler.handleRequest)(FilterHandler.java:84)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest)(ServletSecurityRoleHandler.java:62)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletChain$1.handleRequest](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletChain$1.handleRequest)(ServletChain.java:68)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest)(ServletDispatchingHandler.java:36)
        at [org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest](mailto:org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest)(SecurityContextAssociationHandler.java:78)
        at [io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest](mailto:io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest)(PredicateHandler.java:43)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest)(SSLInformationAssociationHandler.java:132)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest)(ServletAuthenticationCallHandler.java:57)
        at [io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest](mailto:io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest)(PredicateHandler.java:43)
        at [io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest](mailto:io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest)(AbstractConfidentialityHandler.java:46)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest)(ServletConfidentialityConstraintHandler.java:64)
        at [io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest](mailto:io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest)(AuthenticationMechanismsHandler.java:60)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest)(CachedAuthenticatedSessionHandler.java:77)
        at [io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest](mailto:io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest)(NotificationReceiverHandler.java:50)
        at [io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest](mailto:io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest)(AbstractSecurityContextAssociationHandler.java:43)
        at [io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest](mailto:io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest)(PredicateHandler.java:43)
        at [org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest](mailto:org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest)(JACCContextIdHandler.java:61)
        at [io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest](mailto:io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest)(PredicateHandler.java:43)
        at [org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest](mailto:org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest)(GlobalRequestControllerHandler.java:68)
        at [io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest](mailto:io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest)(PredicateHandler.java:43)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest)(ServletInitialHandler.java:292)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.access$100](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.access$100)(ServletInitialHandler.java:81)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$2.call](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$2.call)(ServletInitialHandler.java:138)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$2.call](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$2.call)(ServletInitialHandler.java:135)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call)(ServletRequestContextThreadSetupAction.java:48)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call)(ContextClassLoaderSetupAction.java:43)
        at [org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0](mailto:org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0)(SecurityContextThreadSetupAction.java:105)
        at [org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0](mailto:org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0)(UndertowDeploymentInfoService.java:1502)
        at [org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0](mailto:org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0)(UndertowDeploymentInfoService.java:1502)
        at [org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0](mailto:org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0)(UndertowDeploymentInfoService.java:1502)
        at [org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0](mailto:org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0)(UndertowDeploymentInfoService.java:1502)
        at [org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0](mailto:org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0)(UndertowDeploymentInfoService.java:1502)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest)(ServletInitialHandler.java:272)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.access$000](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.access$000)(ServletInitialHandler.java:81)
        at [io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest](mailto:io.undertow.servlet@2.0.15.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest)(ServletInitialHandler.java:104)
        at [io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.Connectors.executeRootHandler](mailto:io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.Connectors.executeRootHandler)(Connectors.java:360)
        at [io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.HttpServerExchange$1.run](mailto:io.undertow.core@2.0.15.Final-redhat-00001//io.undertow.server.HttpServerExchange$1.run)(HttpServerExchange.java:830)
        at [org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.ContextClassLoaderSavingRunnable.run](mailto:org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.ContextClassLoaderSavingRunnable.run)(ContextClassLoaderSavingRunnable.java:35)
        at [org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.EnhancedQueueExecutor.safeRun](mailto:org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.EnhancedQueueExecutor.safeRun)(EnhancedQueueExecutor.java:1985)
        at [org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask](mailto:org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask)(EnhancedQueueExecutor.java:1487)
        at [org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run](mailto:org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run)(EnhancedQueueExecutor.java:1378)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">

<head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Govern de les Illes Balears</title>
        
        <!-- css -->
        <link href="j_security_check_resource/estilos/estils_intranet.css" rel="stylesheet" type="text/css" media="screen" />
        <!-- /css -->
        
        <script type="text/java"[truncated 4371 chars]; line: 1, column: 2]
        at [com.fasterxml.jackson.core.jackson-core@2.9.5.redhat-2//com.fasterxml.jackson.core.JsonParser._constructError](mailto:com.fasterxml.jackson.core.jackson-core@2.9.5.redhat-2//com.fasterxml.jackson.core.JsonParser._constructError)(JsonParser.java:1804)
        at [com.fasterxml.jackson.core.jackson-core@2.9.5.redhat-2//com.fasterxml.jackson.core.base.ParserMinimalBase._reportError](mailto:com.fasterxml.jackson.core.jackson-core@2.9.5.redhat-2//com.fasterxml.jackson.core.base.ParserMinimalBase._reportError)(ParserMinimalBase.java:663)
        at [com.fasterxml.jackson.core.jackson-core@2.9.5.redhat-2//com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar](mailto:com.fasterxml.jackson.core.jackson-core@2.9.5.redhat-2//com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar)(ParserMinimalBase.java:561)
        at [com.fasterxml.jackson.core.jackson-core@2.9.5.redhat-2//com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue](mailto:com.fasterxml.jackson.core.jackson-core@2.9.5.redhat-2//com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue)(ReaderBasedJsonParser.java:1892)
        at [com.fasterxml.jackson.core.jackson-core@2.9.5.redhat-2//com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken](mailto:com.fasterxml.jackson.core.jackson-core@2.9.5.redhat-2//com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken)(ReaderBasedJsonParser.java:747)
        at [com.fasterxml.jackson.core.jackson-databind@2.9.5.redhat-2//com.fasterxml.jackson.databind.ObjectMapper._initForReading](mailto:com.fasterxml.jackson.core.jackson-databind@2.9.5.redhat-2//com.fasterxml.jackson.databind.ObjectMapper._initForReading)(ObjectMapper.java:4129)
        at [com.fasterxml.jackson.core.jackson-databind@2.9.5.redhat-2//com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose](mailto:com.fasterxml.jackson.core.jackson-databind@2.9.5.redhat-2//com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose)(ObjectMapper.java:3988)
        at [com.fasterxml.jackson.core.jackson-databind@2.9.5.redhat-2//com.fasterxml.jackson.databind.ObjectMapper.readValue](mailto:com.fasterxml.jackson.core.jackson-databind@2.9.5.redhat-2//com.fasterxml.jackson.databind.ObjectMapper.readValue)(ObjectMapper.java:2992)
        at deployment.carpeta.ear//es.caib.notib.client.NotificacioRestClientV2.notificacionsByTitular(NotificacioRestClientV2.java:273)
        ... 90 more

```

**Comment by anadal-fundaciobit** [comment]
No he pogut reproduir l'error ni provar si el parxe de reintents aplicat funciona.
