### ISSUE TITLE
Error en instanciar Plugin Expedients a CARPETA

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/carpeta#857]
En entrar a dins el plugin dels expedients de CARPETA falla just en entrar i no es pot fer cap tipus de cerca:

![image](https://github.com/user-attachments/assets/05c2c11f-f4c1-4f31-b266-66db668824d6)

_2024-09-16 09:11:39,871 INFO  [org.fundaciobit.pluginsib.core.v3.utils.PluginsManager] (default task-86) Carregant classe es.caib.plugins.arxiu.caib.ArxiuPluginCaib ...
2024-09-16 09:11:39,872 ERROR [org.fundaciobit.pluginsib.core.v3.utils.PluginsManager] (default task-86) Error carregant la classe es.caib.plugins.arxiu.caib.ArxiuPluginCaib associada a un plugin:es.caib.plugins.arxiu.caib.ArxiuPluginCaib from [Module "deployment.carpeta.ear" from Service Module Loader]: java.lang.ClassNotFoundException: es.caib.plugins.arxiu.caib.ArxiuPluginCaib from [Module "deployment.carpeta.ear" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)_

_2024-09-16 09:11:39,873 ERROR [org.fundaciobit.pluginsib.carpetafront.expedients.ExpedientsCarpetaFrontPlugin] (default task-86) Error llistant 'Els meus Expedients': No puc instanciar el Plugin d'Arxiu dins del Plugin de Carpeta Front d'Expedients (Classe => es.caib.plugins.arxiu.caib.ArxiuPluginCaib): java.lang.Exception: No puc instanciar el Plugin d'Arxiu dins del Plugin de Carpeta Front d'Expedients (Classe => es.caib.plugins.arxiu.caib.ArxiuPluginCaib)
	at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.expedients.ExpedientsCarpetaFrontPlugin.instanticatePluginArxiu(ExpedientsCarpetaFrontPlugin.java:363)_

_2024-09-16 09:11:39,874 ERROR [org.fundaciobit.pluginsib.carpetafront.expedients.ExpedientsCarpetaFrontPlugin] (default task-86) AbstractPluginFullUtilities::errorREST() No puc instanciar el Plugin d'Arxiu dins del Plugin de Carpeta Front d'Expedients (Classe => es.caib.plugins.arxiu.caib.ArxiuPluginCaib): java.lang.Exception: No puc instanciar el Plugin d'Arxiu dins del Plugin de Carpeta Front d'Expedients (Classe => es.caib.plugins.arxiu.caib.ArxiuPluginCaib)
	at deployment.carpeta.ear//org.fundaciobit.pluginsib.carpetafront.expedients.ExpedientsCarpetaFrontPlugin.instanticatePluginArxiu(ExpedientsCarpetaFrontPlugin.java:363)_

**Comment by anadal-fundaciobit** [comment]
S'ha de substituir el valor de la propietat "es.caib.carpeta.pluginsib.carpetafront.expedients.arxiuclass" de "es.caib.**plugins**.arxiu.caib.ArxiuPluginCaib" a "es.caib.**pluginsib**.arxiu.caib.ArxiuPluginCaib". En resum, ja no és "plugins" sinó "pluginsib"
